CREATE TABLE IF NOT EXISTS todos(
id SERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
is_completed boolean DEFAULT false,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);